# Exercise 4.6 - Task

## Libraries

In [50]:
# Importing Libraries

In [52]:
import pandas as pd
import numpy as np
import os

## Data Sets

In [55]:
#creating path

In [57]:
path=r'/Users/konstant/Documents/Achievement 4. Instacart Basket Analysis'

# 3. Importing Data Set.

In [60]:
df_orders_products_combined=pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_combined.pkl'))

# 4. Checking the shape of the data frame.

In [63]:
df_orders_products_combined.shape

(32434489, 9)

## The data shape matches the shape of the exported data frame.

# 5. Combining 'df_orders_products_combined' with the 'products_checked' data set.

In [67]:
# Firstly importing 'products_checked'

In [69]:
df_products_checked= pd.read_csv(os.path.join(path,'02 Data','Prepared Data','products_checked.csv'),index_col = 0)

In [27]:
# Now checking the headings of both data frames for a merger key.

In [29]:
df_orders_products_combined.head()

,order_id,user_id,order_number,orders_day_of_week,hour_of_purchase,days_since_prior_order,product_id,add_to_cart_order,reordered
0,2539329,1,1,2,8,NaN,196,1,0
1,2539329,1,1,2,8,NaN,14084,2,0
2,2539329,1,1,2,8,NaN,12427,3,0
3,2539329,1,1,2,8,NaN,26088,4,0
4,2539329,1,1,2,8,NaN,26405,5,0

In [31]:
df_products_checked.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [33]:
# 'product_id' identified as the key. Proceeding to merge with a inner join.

In [35]:
df_ords_prods_merge=df_products_checked.merge(df_orders_products_combined,on=['product_id'],indicator=True)

In [37]:
df_ords_prods_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,hour_of_purchase,days_since_prior_order,add_to_cart_order,reordered,_merge
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,10,0,both
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both

# 6. Confirming the results of the merge with the merge flag.

In [40]:
df_ords_prods_merge['_merge'].value_counts()

_merge
both          32404859
left_only            0
right_only           0
Name: count, dtype: int64

# 7. Exporting dataframe.

## Exporting in pickle format due to it‘s size.

In [44]:
df_ords_prods_merge.to_pickle(os.path.join(path,'02 Data','Prepared Data','ords_prods_merge.pkl'))

In [45]:
df_ords_prods_merge.shape

(32404859, 14)