# Exercise 4.9 - part 1.

## Table of content
3.1 Importing Libraries

3.2 Importing Data Sets

4. Data Wrangling
5. Data quality and consistency checks
6. Merging data frames
7. Exporting Data Frame

## 3.1. Importing Libraries

In [25]:
#Importing analysis libraries

In [27]:
import pandas as pd
import numpy as np
import os

## 3.2. Importing Data Sets

In [30]:
# Creating path

In [32]:
path = r'/Users/konstant/Documents/Achievement 4. Instacart Basket Analysis'

In [34]:
# Importing 'Customer Data' set

In [36]:
df_customers= pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'customers 2.csv'), index_col = False)

In [38]:
df_customers.shape

(206209, 10)

### Exploring the 'customers' data set.

In [41]:
# Checking the column headers

In [43]:
df_customers.head()

,user_id,First Name,Surnam,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

In [45]:
# Checkign the shape of the data frame

In [47]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206209 entries, 0 to 206208
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   user_id       206209 non-null  int64
 1   First Name    194950 non-null  object
 2   Surnam        206209 non-null  object
 3   Gender        206209 non-null  object
 4   STATE         206209 non-null  object
 5   Age           206209 non-null  int64
 6   date_joined   206209 non-null  object
 7   n_dependants  206209 non-null  int64
 8   fam_status    206209 non-null  object
 9   income        206209 non-null  int64
dtypes: int64(4), object(6)
memory usage: 15.7+ MB

### 206,209 rows, 10 columns. The data type is a mix of numbers (int64) and textual (object).

# 4. Data Wrangling

In [51]:
# Checking headers to rename.

In [53]:
df_customers.head(2)

,user_id,First Name,Surnam,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285

## Renaming columns to keep the formatting uniform:

In [56]:
# Renaming the column 'First Name' to 'first_name'

In [58]:
df_customers.rename(columns={'First Name':'first_name'},inplace=True)

In [60]:
# Renaming the column 'Surname' to 'last_name'

In [62]:
df_customers.rename(columns={'Surnam':'last_name'},inplace=True)

In [64]:
# Renaming column 'Gender' to 'gender'

In [66]:
df_customers.rename(columns={'Gender':'gender'},inplace=True)

In [68]:
# Renaming column 'STATE' to 'state'

In [70]:
df_customers.rename(columns={'STATE':'state'},inplace=True)

In [72]:
# Renaming column 'Age' to 'age'

In [74]:
df_customers.rename(columns={'Age':'age'},inplace=True)

In [76]:
# Renaming column 'n_dependants' to 'num_of_dependants'

In [78]:
df_customers.rename(columns={'n_dependants':'num_of_dependants'},inplace=True)

In [80]:
# Checking results of the renaming

In [82]:
df_customers.head(2)

,user_id,first_name,last_name,gender,state,age,date_joined,num_of_dependants,fam_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285

# 5. Data quality and consistency checks

## Checking the basic statistical analyis of the data frame:

In [86]:
df_customers.describe(pd.set_option('display.float_format', '{:.2f}'.format)
)

        user_id       age  num_of_dependants    income
count 206209.00 206209.00          206209.00 206209.00
mean  103105.00     49.50               1.50  94632.85
std    59527.56     18.48               1.12  42473.79
min        1.00     18.00               0.00  25903.00
25%    51553.00     33.00               0.00  59874.00
50%   103105.00     49.00               1.00  93547.00
75%   154657.00     66.00               3.00 124244.00
max   206209.00     81.00               3.00 593901.00

### -The discriptive statistics looks normal.

## Checking for mixed data types

In [90]:
# Now checking for mixed data types

In [92]:
for col in df_customers.columns.tolist():
  weird = (df_customers[[col]].map(type) != df_customers[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_customers[weird]) > 0:
    print (col)

first_name

### -Mixed data type identified in the column:'first_name'

### -Addressing the mixed data type column.

In [96]:
df_customers['first_name'] = df_customers['first_name'].astype('str')

In [98]:
# checking if the deployment was successul:

In [100]:
for col in df_customers.columns.tolist():
  weird = (df_customers[[col]].map(type) != df_customers[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_customers[weird]) > 0:
    print (col)

### -There seems to be no mixed data types left.

## Checking for missing values

In [104]:
# Now checking for missing values:

In [106]:
df_customers.isnull().sum()

user_id              0
first_name           0
last_name            0
gender               0
state                0
age                  0
date_joined          0
num_of_dependants    0
fam_status           0
income               0
dtype: int64

### -No missing values identified

## Checking for duplicated values

In [110]:
# Now checking for duplicated values.

In [112]:
df_customers[df_customers.duplicated()]

Empty DataFrame
Columns: [user_id, first_name, last_name, gender, state, age, date_joined, num_of_dependants, fam_status, income]
Index: []

### -No duplicated values found.

# 6. Merging data frames

In [116]:
#Importing 'ords_prods_merge_aggregated_variables' data set

In [118]:
df_ords_prods_merge_aggregated_variables= pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ords_prods_merge_aggregated_variables.pkl'))

In [120]:
#Checking the column heads

In [122]:
df_ords_prods_merge_aggregated_variables.head(2)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,hour_of_purchase,...,_merge,price_range_loc,busiest_days,busiest_period_of_day,max_order,loyalty_flag,max_spend,spending_flag,days_since_last_order_median,order_frequency_flag
0,1,Chocolate Sandwich Cookies,61,19,5.80,3139998,138,28,6,11,...,both,Mid-range product,Regular days,"Most orders,",32,Regular customer,20.00,High spender,8.00,Frequent customer
1,1,Chocolate Sandwich Cookies,61,19,5.80,1977647,138,30,6,17,...,both,Mid-range product,Regular days,"Average orders,",32,Regular customer,20.00,High spender,8.00,Frequent customer

In [124]:
# Dropping the indicator column (_merge) that already exists on the data frame

In [126]:
df_ords_prods_merge_aggregated_variables.drop(columns=['_merge'],inplace=True,errors='ignore')

In [128]:
# Merging the 'customers' data frame with the 'ords_prods_merge_aggregated_variables'

In [ ]:
df_final_merge=df_ords_prods_merge_aggregated_variables.merge(df_customers,on=['user_id'],indicator=True)

In [111]:
# Checking th results of the merge.

In [113]:
df_final_merge.head(2)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,hour_of_purchase,...,first_name,last_name,gender,state,age,date_joined,num_of_dependants,fam_status,income,_merge
0,1,Chocolate Sandwich Cookies,61,19,5.80,3139998,138,28,6,11,...,Charles,Cox,Male,Minnesota,81,8/1/2019,1,married,49620,both
1,1,Chocolate Sandwich Cookies,61,19,5.80,1977647,138,30,6,17,...,Charles,Cox,Male,Minnesota,81,8/1/2019,1,married,49620,both

# 8. Exporting Data Frame

In [116]:
# exporting the data frame as a pickel file.

In [118]:
df_final_merge.to_pickle(os.path.join(path,'02 Data','Prepared Data','df_final_merge.pkl'))